# QuranNode — desktop simulator build.
#
# Builds the portable core (core/) + the SDL HAL (hal/sim) + the harness (sim/)
# into a single native binary you can run on macOS/Linux to iterate the UX. The
# same core/ sources compile unchanged into the ESP32-S3 firmware (firmware/,
# added at M2) against hal/esp32.

BIN      := quran-sim
BUILD    := build

CC       := cc
CXX      := c++
SDL_CFLAGS := $(shell pkg-config --cflags sdl2)
SDL_LIBS   := $(shell pkg-config --libs sdl2)
ST_CFLAGS  := $(shell pkg-config --cflags soundtouch)
ST_LIBS    := $(shell pkg-config --libs soundtouch)

INCLUDES := -Icore -Icore/gfx -Icore/arabic -Icore/quran -Icore/audio -Icore/scene -Ihal
CFLAGS   := -std=c11 -O2 -g -Wall -Wextra -Wno-unused-parameter -MMD -MP $(INCLUDES) $(SDL_CFLAGS)
CXXFLAGS := -std=c++14 -O2 -g -Wall -Wextra -Wno-unused-parameter -MMD -MP $(INCLUDES) $(SDL_CFLAGS) $(ST_CFLAGS)
LDFLAGS  := $(SDL_LIBS) $(ST_LIBS) -lm

# Portable core (compiles for both sim and firmware).
CORE_SRCS := \
  $(wildcard core/*.c) \
  $(wildcard core/gfx/*.c) \
  $(wildcard core/arabic/*.c) \
  $(wildcard core/quran/*.c) \
  $(wildcard core/audio/*.c) \
  $(wildcard core/scene/*.c)

# Simulator = core + SDL HAL (C) + audio HAL (C++) + harness.
SIM_C_SRCS := $(CORE_SRCS) hal/sim/hal_sim.c sim/main.c
SIM_CPP_SRCS := hal/sim/audio_sim.cpp
OBJS := $(patsubst %.c,$(BUILD)/%.o,$(SIM_C_SRCS)) \
        $(patsubst %.cpp,$(BUILD)/%.o,$(SIM_CPP_SRCS))

# Headless frame dumper = core + tools/dump_frame.c (no SDL/audio).
DUMP_SRCS := $(CORE_SRCS) tools/dump_frame.c
DUMP_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(DUMP_SRCS))

.PHONY: all run clean dump loop-test qdb-test hifz-drill-test
all: $(BIN)

# Invariants for the generated Quran metadata (global ayah index + page tables).
qdb-test:
	$(CC) -std=c11 -O2 $(INCLUDES) tools/qdb_test.c core/quran/quran_db.c \
	      -o quran-qdb-test
	./quran-qdb-test

# Reading-coverage engine: dwell crediting, page math, persistence, day rollover.
khatm-test:
	$(CC) -std=c11 -O2 $(INCLUDES) tools/khatm_test.c core/quran/khatm.c core/quran/qday.c \
	      core/quran/quran_db.c -o quran-khatm-test -lm
	./quran-khatm-test

# Memorization scheduler: tier transitions, intervals, plan, persistence, clock.
hifz-test:
	$(CC) -std=c11 -O2 $(INCLUDES) tools/hifz_test.c core/quran/hifz.c \
	      core/quran/qday.c core/quran/quran_db.c -o quran-hifz-test -lm
	./quran-hifz-test

# Deterministic unit test for the Ayah Loop engine (no SDL/audio).
loop-test:
	$(CC) -std=c11 -O2 $(INCLUDES) tools/loop_test.c core/audio/player.c \
	      core/quran/timing.c -o quran-loop-test -lm
	./quran-loop-test

# Talqeen drill phase machine: exact phase sequence, sliding connect windows,
# NO/SHAKY branches, peek cap, grade bookkeeping, player restore (no SDL/audio).
hifz-drill-test:
	$(CC) -std=c11 -O2 $(INCLUDES) tools/hifz_drill_test.c core/quran/hifz_drill.c \
	      core/audio/player.c core/quran/timing.c core/quran/quran_db.c \
	      -o quran-hifz-drill-test -lm
	./quran-hifz-drill-test

# Host-side batch evaluator: replay labeled training WAVs (from the teacher's
# TRAIN mode) through recite_analyze against the real reference + timings.
recite-eval:
	$(CC) -std=c11 -O2 $(INCLUDES) -Ihal/sim/vendor tools/recite_eval.c \
	      core/audio/recite.c -o quran-recite-eval -lm
	@echo "built ./quran-recite-eval"

# Link with the C++ driver (pulls in libc++ for the SoundTouch TU).
$(BIN): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)
	@echo "built ./$(BIN)"

# quran-dump has no SDL dependency (uses -Ihal for hal.h only).
quran-dump: $(DUMP_OBJS)
	$(CC) $(DUMP_OBJS) -o $@ -lm
	@echo "built ./quran-dump"

dump: quran-dump

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

run: all
	./$(BIN)

clean:
	rm -rf $(BUILD) $(BIN) quran-dump quran-loop-test quran-qdb-test quran-khatm-test quran-hifz-test quran-hifz-drill-test

# Header-dependency files (generated by -MMD) so header edits trigger rebuilds.
-include $(OBJS:.o=.d) $(DUMP_OBJS:.o=.d)
