# QuranNode — desktop simulator build.
#
# Builds the portable core (core/) + the SDL HAL (hal/sim) + the harness (sim/)
# into a single native binary you can run on macOS/Linux to iterate the UX. The
# same core/ sources compile unchanged into the ESP32-S3 firmware (firmware/,
# added at M2) against hal/esp32.

BIN      := quran-sim
BUILD    := build

CC       := cc
CXX      := c++
SDL_CFLAGS := $(shell pkg-config --cflags sdl2)
SDL_LIBS   := $(shell pkg-config --libs sdl2)
ST_CFLAGS  := $(shell pkg-config --cflags soundtouch)
ST_LIBS    := $(shell pkg-config --libs soundtouch)

INCLUDES := -Icore -Icore/gfx -Icore/arabic -Icore/quran -Icore/audio -Icore/scene -Ihal
CFLAGS   := -std=c11 -O2 -g -Wall -Wextra -Wno-unused-parameter -MMD -MP $(INCLUDES) $(SDL_CFLAGS)
CXXFLAGS := -std=c++14 -O2 -g -Wall -Wextra -Wno-unused-parameter -MMD -MP $(INCLUDES) $(SDL_CFLAGS) $(ST_CFLAGS)
LDFLAGS  := $(SDL_LIBS) $(ST_LIBS) -lm

# Portable core (compiles for both sim and firmware).
CORE_SRCS := \
  $(wildcard core/*.c) \
  $(wildcard core/gfx/*.c) \
  $(wildcard core/arabic/*.c) \
  $(wildcard core/quran/*.c) \
  $(wildcard core/audio/*.c) \
  $(wildcard core/scene/*.c)

# Simulator = core + SDL HAL (C) + audio HAL (C++) + harness.
SIM_C_SRCS := $(CORE_SRCS) hal/sim/hal_sim.c sim/main.c
SIM_CPP_SRCS := hal/sim/audio_sim.cpp
OBJS := $(patsubst %.c,$(BUILD)/%.o,$(SIM_C_SRCS)) \
        $(patsubst %.cpp,$(BUILD)/%.o,$(SIM_CPP_SRCS))

# Headless frame dumper = core + tools/dump_frame.c (no SDL/audio).
DUMP_SRCS := $(CORE_SRCS) tools/dump_frame.c
DUMP_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(DUMP_SRCS))

.PHONY: all run clean dump loop-test
all: $(BIN)

# Deterministic unit test for the Ayah Loop engine (no SDL/audio).
loop-test:
	$(CC) -std=c11 -O2 $(INCLUDES) tools/loop_test.c core/audio/player.c \
	      core/quran/timing.c -o quran-loop-test -lm
	./quran-loop-test

# Link with the C++ driver (pulls in libc++ for the SoundTouch TU).
$(BIN): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)
	@echo "built ./$(BIN)"

# quran-dump has no SDL dependency (uses -Ihal for hal.h only).
quran-dump: $(DUMP_OBJS)
	$(CC) $(DUMP_OBJS) -o $@ -lm
	@echo "built ./quran-dump"

dump: quran-dump

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

run: all
	./$(BIN)

clean:
	rm -rf $(BUILD) $(BIN) quran-dump quran-loop-test

# Header-dependency files (generated by -MMD) so header edits trigger rebuilds.
-include $(OBJS:.o=.d) $(DUMP_OBJS:.o=.d)
