// quran_db.h — Quran metadata (surahs + juz). GENERATED by tools/build_db.py.
#pragma once
#include <stdint.h>

typedef struct { int surah, ayah; } QRef;

typedef struct {
    const char *name_en;   // e.g. "Al-Fatihah"
    const char *name_ar;   // UTF-8 Arabic name (for glyph-pack rendering)
    uint16_t    ayat;      // number of ayat
    uint8_t     makki;     // 1 = Meccan, 0 = Medinan
} SurahInfo;

#define QDB_SURAH_COUNT 114
#define QDB_JUZ_COUNT   30

const SurahInfo *qdb_surah(int surah);   // 1-based; NULL if out of range
const char *qdb_surah_name(int surah);   // English name, "" if invalid
int  qdb_ayah_count(int surah);
QRef qdb_juz_start(int juz);             // 1-based
int  qdb_juz_of(int surah, int ayah);    // which juz a ref falls in (1..30)
