// quran_db.c — GENERATED by tools/build_db.py. Do not edit by hand.
#include "quran_db.h"
#include <stddef.h>

static const SurahInfo SURAHS[QDB_SURAH_COUNT] = {
    { "Al-Fatihah", "الفاتحة", 7, 1 },
    { "Al-Baqarah", "البقرة", 286, 0 },
    { "Ali 'Imran", "آل عمران", 200, 0 },
    { "An-Nisa", "النساء", 176, 0 },
    { "Al-Ma'idah", "المائدة", 120, 0 },
    { "Al-An'am", "الأنعام", 165, 1 },
    { "Al-A'raf", "الأعراف", 206, 1 },
    { "Al-Anfal", "الأنفال", 75, 0 },
    { "At-Tawbah", "التوبة", 129, 0 },
    { "Yunus", "يونس", 109, 1 },
    { "Hud", "هود", 123, 1 },
    { "Yusuf", "يوسف", 111, 1 },
    { "Ar-Ra'd", "الرعد", 43, 0 },
    { "Ibrahim", "ابراهيم", 52, 1 },
    { "Al-Hijr", "الحجر", 99, 1 },
    { "An-Nahl", "النحل", 128, 1 },
    { "Al-Isra", "الإسراء", 111, 1 },
    { "Al-Kahf", "الكهف", 110, 1 },
    { "Maryam", "مريم", 98, 1 },
    { "Taha", "طه", 135, 1 },
    { "Al-Anbya", "الأنبياء", 112, 1 },
    { "Al-Hajj", "الحج", 78, 0 },
    { "Al-Mu'minun", "المؤمنون", 118, 1 },
    { "An-Nur", "النور", 64, 0 },
    { "Al-Furqan", "الفرقان", 77, 1 },
    { "Ash-Shu'ara", "الشعراء", 227, 1 },
    { "An-Naml", "النمل", 93, 1 },
    { "Al-Qasas", "القصص", 88, 1 },
    { "Al-'Ankabut", "العنكبوت", 69, 1 },
    { "Ar-Rum", "الروم", 60, 1 },
    { "Luqman", "لقمان", 34, 1 },
    { "As-Sajdah", "السجدة", 30, 1 },
    { "Al-Ahzab", "الأحزاب", 73, 0 },
    { "Saba", "سبإ", 54, 1 },
    { "Fatir", "فاطر", 45, 1 },
    { "Ya-Sin", "يس", 83, 1 },
    { "As-Saffat", "الصافات", 182, 1 },
    { "Sad", "ص", 88, 1 },
    { "Az-Zumar", "الزمر", 75, 1 },
    { "Ghafir", "غافر", 85, 1 },
    { "Fussilat", "فصلت", 54, 1 },
    { "Ash-Shuraa", "الشورى", 53, 1 },
    { "Az-Zukhruf", "الزخرف", 89, 1 },
    { "Ad-Dukhan", "الدخان", 59, 1 },
    { "Al-Jathiyah", "الجاثية", 37, 1 },
    { "Al-Ahqaf", "الأحقاف", 35, 1 },
    { "Muhammad", "محمد", 38, 0 },
    { "Al-Fath", "الفتح", 29, 0 },
    { "Al-Hujurat", "الحجرات", 18, 0 },
    { "Qaf", "ق", 45, 1 },
    { "Adh-Dhariyat", "الذاريات", 60, 1 },
    { "At-Tur", "الطور", 49, 1 },
    { "An-Najm", "النجم", 62, 1 },
    { "Al-Qamar", "القمر", 55, 1 },
    { "Ar-Rahman", "الرحمن", 78, 0 },
    { "Al-Waqi'ah", "الواقعة", 96, 1 },
    { "Al-Hadid", "الحديد", 29, 0 },
    { "Al-Mujadila", "المجادلة", 22, 0 },
    { "Al-Hashr", "الحشر", 24, 0 },
    { "Al-Mumtahanah", "الممتحنة", 13, 0 },
    { "As-Saf", "الصف", 14, 0 },
    { "Al-Jumu'ah", "الجمعة", 11, 0 },
    { "Al-Munafiqun", "المنافقون", 11, 0 },
    { "At-Taghabun", "التغابن", 18, 0 },
    { "At-Talaq", "الطلاق", 12, 0 },
    { "At-Tahrim", "التحريم", 12, 0 },
    { "Al-Mulk", "الملك", 30, 1 },
    { "Al-Qalam", "القلم", 52, 1 },
    { "Al-Haqqah", "الحاقة", 52, 1 },
    { "Al-Ma'arij", "المعارج", 44, 1 },
    { "Nuh", "نوح", 28, 1 },
    { "Al-Jinn", "الجن", 28, 1 },
    { "Al-Muzzammil", "المزمل", 20, 1 },
    { "Al-Muddaththir", "المدثر", 56, 1 },
    { "Al-Qiyamah", "القيامة", 40, 1 },
    { "Al-Insan", "الانسان", 31, 0 },
    { "Al-Mursalat", "المرسلات", 50, 1 },
    { "An-Naba", "النبإ", 40, 1 },
    { "An-Nazi'at", "النازعات", 46, 1 },
    { "'Abasa", "عبس", 42, 1 },
    { "At-Takwir", "التكوير", 29, 1 },
    { "Al-Infitar", "الإنفطار", 19, 1 },
    { "Al-Mutaffifin", "المطففين", 36, 1 },
    { "Al-Inshiqaq", "الإنشقاق", 25, 1 },
    { "Al-Buruj", "البروج", 22, 1 },
    { "At-Tariq", "الطارق", 17, 1 },
    { "Al-A'la", "الأعلى", 19, 1 },
    { "Al-Ghashiyah", "الغاشية", 26, 1 },
    { "Al-Fajr", "الفجر", 30, 1 },
    { "Al-Balad", "البلد", 20, 1 },
    { "Ash-Shams", "الشمس", 15, 1 },
    { "Al-Layl", "الليل", 21, 1 },
    { "Ad-Duhaa", "الضحى", 11, 1 },
    { "Ash-Sharh", "الشرح", 8, 1 },
    { "At-Tin", "التين", 8, 1 },
    { "Al-'Alaq", "العلق", 19, 1 },
    { "Al-Qadr", "القدر", 5, 1 },
    { "Al-Bayyinah", "البينة", 8, 0 },
    { "Az-Zalzalah", "الزلزلة", 8, 0 },
    { "Al-'Adiyat", "العاديات", 11, 1 },
    { "Al-Qari'ah", "القارعة", 11, 1 },
    { "At-Takathur", "التكاثر", 8, 1 },
    { "Al-'Asr", "العصر", 3, 1 },
    { "Al-Humazah", "الهمزة", 9, 1 },
    { "Al-Fil", "الفيل", 5, 1 },
    { "Quraysh", "قريش", 4, 1 },
    { "Al-Ma'un", "الماعون", 7, 1 },
    { "Al-Kawthar", "الكوثر", 3, 1 },
    { "Al-Kafirun", "الكافرون", 6, 1 },
    { "An-Nasr", "النصر", 3, 0 },
    { "Al-Masad", "المسد", 5, 1 },
    { "Al-Ikhlas", "الإخلاص", 4, 1 },
    { "Al-Falaq", "الفلق", 5, 1 },
    { "An-Nas", "الناس", 6, 1 },
};

static const QRef JUZ_START[QDB_JUZ_COUNT] = {
    { 1, 1 },
    { 2, 142 },
    { 2, 253 },
    { 3, 93 },
    { 4, 24 },
    { 4, 148 },
    { 5, 82 },
    { 6, 111 },
    { 7, 88 },
    { 8, 41 },
    { 9, 93 },
    { 11, 6 },
    { 12, 53 },
    { 15, 1 },
    { 17, 1 },
    { 18, 75 },
    { 21, 1 },
    { 23, 1 },
    { 25, 21 },
    { 27, 56 },
    { 29, 46 },
    { 33, 31 },
    { 36, 28 },
    { 39, 32 },
    { 41, 47 },
    { 46, 1 },
    { 51, 31 },
    { 58, 1 },
    { 67, 1 },
    { 78, 1 },
};

const SurahInfo *qdb_surah(int surah) {
    if (surah < 1 || surah > QDB_SURAH_COUNT) return NULL;
    return &SURAHS[surah - 1];
}
const char *qdb_surah_name(int surah) {
    const SurahInfo *s = qdb_surah(surah);
    return s ? s->name_en : "";
}
int qdb_ayah_count(int surah) {
    const SurahInfo *s = qdb_surah(surah);
    return s ? s->ayat : 0;
}
QRef qdb_juz_start(int juz) {
    if (juz < 1 || juz > QDB_JUZ_COUNT) { QRef z = {0, 0}; return z; }
    return JUZ_START[juz - 1];
}
int qdb_juz_of(int surah, int ayah) {
    int found = 1;
    for (int j = 0; j < QDB_JUZ_COUNT; j++) {
        int s = JUZ_START[j].surah, a = JUZ_START[j].ayah;
        if (surah > s || (surah == s && ayah >= a)) found = j + 1;
        else break;
    }
    return found;
}
