// waqf.h — pause-mark breakpoints for the memorization chunker.
//
// The Uthmani text carries waqf (pause) signs the reciter stops at. When the
// hifz chunker has to split an over-long ayah into screen-sized segments, it
// cuts at these marks instead of at arbitrary word intervals, so each segment
// is a natural phrase. The table is generated by tools/build_waqf_db.py from
// quran-uthmani-waqf.txt (same word split as qdb_word_count).
#pragma once

// 0-based word indices with a pause AFTER them for `surah:ayah`, written sorted
// ascending into `out`. Returns the count (<= max); 0 if the ayah has none.
int waqf_marks(int surah, int ayah, unsigned char *out, int max);
