// GENERATED by tools/gen_embedded.py — Al-Fatihah bundled in flash.
#pragma once
#include <stdint.h>
#include <stddef.h>

extern const uint8_t qn_pack_lg[];
extern const size_t qn_pack_lg_len;
extern const uint8_t qn_pack_lg_tj[];
extern const size_t qn_pack_lg_tj_len;
extern const uint8_t qn_qtm1[];
extern const size_t qn_qtm1_len;
extern const uint8_t qn_mp3_1[];
extern const size_t qn_mp3_1_len;
extern const uint8_t qn_mp3_2[];
extern const size_t qn_mp3_2_len;
extern const uint8_t qn_mp3_3[];
extern const size_t qn_mp3_3_len;
extern const uint8_t qn_mp3_4[];
extern const size_t qn_mp3_4_len;
extern const uint8_t qn_mp3_5[];
extern const size_t qn_mp3_5_len;
extern const uint8_t qn_mp3_6[];
extern const size_t qn_mp3_6_len;
extern const uint8_t qn_mp3_7[];
extern const size_t qn_mp3_7_len;
