#!/usr/bin/env python3
"""build_db.py — generate core/quran/quran_db.{c,h} from the Quran.com API.

Fetches the 114 chapters (English + Arabic name, ayah count, revelation place)
and the 30 juz boundaries, and emits a compiled-in C table. Metadata is tiny and
always needed, so it lives in flash rather than on the SD card. Re-run to refresh.
"""
import json
import os
import urllib.request

UA = "Mozilla/5.0 QuranNode/0.1"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C = os.path.join(ROOT, "core", "quran", "quran_db.c")
OUT_H = os.path.join(ROOT, "core", "quran", "quran_db.h")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    chapters = get("https://api.quran.com/api/v4/chapters")["chapters"]
    juzs = get("https://api.quran.com/api/v4/juzs")["juzs"]

    chapters.sort(key=lambda c: c["id"])

    # Juz start = the earliest surah:ayah in its verse_mapping.
    juz_start = {}
    for j in juzs:
        n = j["juz_number"]
        best = None
        for surah, rng in j["verse_mapping"].items():
            a0 = int(str(rng).split("-")[0])
            ref = (int(surah), a0)
            if best is None or ref < best:
                best = ref
        juz_start[n] = best

    with open(OUT_H, "w") as f:
        f.write("""// quran_db.h — Quran metadata (surahs + juz). GENERATED by tools/build_db.py.
#pragma once
#include <stdint.h>

typedef struct { int surah, ayah; } QRef;

typedef struct {
    const char *name_en;   // e.g. "Al-Fatihah"
    const char *name_ar;   // UTF-8 Arabic name (for glyph-pack rendering)
    uint16_t    ayat;      // number of ayat
    uint8_t     makki;     // 1 = Meccan, 0 = Medinan
} SurahInfo;

#define QDB_SURAH_COUNT 114
#define QDB_JUZ_COUNT   30

const SurahInfo *qdb_surah(int surah);   // 1-based; NULL if out of range
const char *qdb_surah_name(int surah);   // English name, "" if invalid
int  qdb_ayah_count(int surah);
QRef qdb_juz_start(int juz);             // 1-based
int  qdb_juz_of(int surah, int ayah);    // which juz a ref falls in (1..30)
""")

    with open(OUT_C, "w") as f:
        f.write('// quran_db.c — GENERATED by tools/build_db.py. Do not edit by hand.\n')
        f.write('#include "quran_db.h"\n#include <stddef.h>\n\n')
        f.write("static const SurahInfo SURAHS[QDB_SURAH_COUNT] = {\n")
        for c in chapters:
            f.write("    { %s, %s, %d, %d },\n" % (
                c_str(c["name_simple"]),
                c_str(c["name_arabic"]),
                c["verses_count"],
                1 if c["revelation_place"] == "makkah" else 0,
            ))
        f.write("};\n\n")

        f.write("static const QRef JUZ_START[QDB_JUZ_COUNT] = {\n")
        for n in range(1, 31):
            s, a = juz_start[n]
            f.write("    { %d, %d },\n" % (s, a))
        f.write("};\n\n")

        f.write("""const SurahInfo *qdb_surah(int surah) {
    if (surah < 1 || surah > QDB_SURAH_COUNT) return NULL;
    return &SURAHS[surah - 1];
}
const char *qdb_surah_name(int surah) {
    const SurahInfo *s = qdb_surah(surah);
    return s ? s->name_en : "";
}
int qdb_ayah_count(int surah) {
    const SurahInfo *s = qdb_surah(surah);
    return s ? s->ayat : 0;
}
QRef qdb_juz_start(int juz) {
    if (juz < 1 || juz > QDB_JUZ_COUNT) { QRef z = {0, 0}; return z; }
    return JUZ_START[juz - 1];
}
int qdb_juz_of(int surah, int ayah) {
    int found = 1;
    for (int j = 0; j < QDB_JUZ_COUNT; j++) {
        int s = JUZ_START[j].surah, a = JUZ_START[j].ayah;
        if (surah > s || (surah == s && ayah >= a)) found = j + 1;
        else break;
    }
    return found;
}
""")
    print("wrote", OUT_C, "and", OUT_H)
    print("surahs:", len(chapters), "juz starts:", len(juz_start))


if __name__ == "__main__":
    main()
