#!/usr/bin/env python3
# build_waqf_db.py — bake waqf (pause) breakpoints into core/quran/waqf.c.
#
# The chunker splits over-long ayat (2:282 is 128 words) into screen-sized
# segments. Cutting at even word intervals lands mid-phrase; cutting at a waqf
# mark lands where a reciter would actually pause — pedagogically the right seam.
#
# tools/build_waqf_text.py injects waqf-sign codepoints into the Uthmani text
# WITHOUT adding spaces, so the marks attach to the end of the word they follow
# and word counts stay identical to quran-uthmani.txt (the qdb_word_count split).
# This reads that file and, per ayah, records the 0-based indices of words with a
# pause after them. Purely LOCAL — no network.
#
# Output: core/quran/waqf.c, a flat sorted table + waqf_marks(). ~4400 marks; at
# 4 bytes each that's ~18 KB of flash, read only when a long ayah is split.
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tools", "quran-tajweed", "quran-uthmani-waqf.txt")
OUT = os.path.join(ROOT, "core", "quran", "waqf.c")

# Waqf signs (Tanzil): 0x06D6..0x06DC + the sajdah 0x06E9. Excludes the ayah-end
# rosette (0x06DD), rub-el-hizb (0x06DE) and tatweel — matches build_waqf_text.py.
WAQF = set(range(0x06D6, 0x06DD)) | {0x06E9}


def main():
    marks = []   # (surah, ayah, word_index)
    with open(SRC, encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("|")
            if len(p) < 3 or not p[0].isdigit():
                continue
            surah, ayah = int(p[0]), int(p[1])
            for i, w in enumerate(p[2].split(" ")):
                if any(ord(c) in WAQF for c in w):
                    marks.append((surah, ayah, i))
    marks.sort()

    with open(OUT, "w") as o:
        o.write("// waqf.c — GENERATED by tools/build_waqf_db.py. Do not edit by hand.\n")
        o.write("// Word indices with a pause (waqf) mark after them, per ayah.\n")
        o.write('#include "waqf.h"\n\n')
        o.write(f"#define WAQF_N {len(marks)}\n\n")
        # Parallel arrays avoid struct padding. surah + word fit in a byte.
        o.write("static const unsigned char  WS[WAQF_N] = {")
        o.write(",".join(str(s) for s, a, w in marks))
        o.write("};\n")
        o.write("static const unsigned short WA[WAQF_N] = {")
        o.write(",".join(str(a) for s, a, w in marks))
        o.write("};\n")
        o.write("static const unsigned char  WW[WAQF_N] = {")
        o.write(",".join(str(w) for s, a, w in marks))
        o.write("};\n\n")
        o.write(
            "int waqf_marks(int surah, int ayah, unsigned char *out, int max)\n"
            "{\n"
            "    int n = 0;\n"
            "    for (int i = 0; i < WAQF_N; i++) {\n"
            "        if (WS[i] != surah) continue;\n"
            "        if (WA[i] != ayah) continue;\n"
            "        if (n < max) out[n] = WW[i];\n"
            "        n++;\n"
            "    }\n"
            "    return n < max ? n : max;\n"
            "}\n"
        )
    print(f"wrote {OUT}: {len(marks)} waqf marks")


if __name__ == "__main__":
    main()
