#!/usr/bin/env python3
"""gen_embedded.py — bundle Al-Fatihah assets into C source arrays.

PlatformIO's espidf embed mechanisms don't reliably emit the _binary_* symbols,
so we compile the assets as plain C arrays instead. To keep any single translation
unit small (the packs total several MB), each asset is written to its OWN .c file
(the qn component globs drivers/*.c) plus a shared header. Regenerate after
changing the glyph packs / audio.

Writes firmware/components/qn/drivers/emb_<sym>.c + embedded_assets.h.
"""
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SD = os.path.join(ROOT, "sdcard")
DRV = os.path.join(ROOT, "firmware", "components", "qn", "drivers")
OUT_H = os.path.join(DRV, "embedded_assets.h")

# (C symbol, relative path the firmware requests via hal_fs_slurp)
# No-SD safety net only: Al-Fatihah at the default Large size (plain + tajweed)
# plus its recitation. All other sizes/surahs live on the SD card.
ASSETS = [
    ("qn_pack_lg",  "packs/reader_lg/1.qgp"),
    ("qn_pack_lg_tj",  "packs/reader_lg_tj/1.qgp"),
    ("qn_qtm1",  "quran/timings/1.qtm"),
    ("qn_mp3_1", "audio/abdulbasit/1/1.mp3"),
    ("qn_mp3_2", "audio/abdulbasit/1/2.mp3"),
    ("qn_mp3_3", "audio/abdulbasit/1/3.mp3"),
    ("qn_mp3_4", "audio/abdulbasit/1/4.mp3"),
    ("qn_mp3_5", "audio/abdulbasit/1/5.mp3"),
    ("qn_mp3_6", "audio/abdulbasit/1/6.mp3"),
    ("qn_mp3_7", "audio/abdulbasit/1/7.mp3"),
]


def main():
    # Clear old generated files so renamed/removed assets don't linger.
    for old in glob.glob(os.path.join(DRV, "emb_*.c")) + [os.path.join(DRV, "embedded_assets.c")]:
        if os.path.exists(old):
            os.remove(old)

    with open(OUT_H, "w") as h:
        h.write("// GENERATED by tools/gen_embedded.py — Al-Fatihah bundled in flash.\n")
        h.write("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n")
        for sym, _ in ASSETS:
            h.write(f"extern const uint8_t {sym}[];\n")
            h.write(f"extern const size_t {sym}_len;\n")

    total = 0
    for sym, rel in ASSETS:
        data = open(os.path.join(SD, rel), "rb").read()
        total += len(data)
        with open(os.path.join(DRV, f"emb_{sym}.c"), "w") as c:
            c.write(f'// GENERATED by tools/gen_embedded.py — {rel}\n')
            c.write('#include "embedded_assets.h"\n\n')
            c.write(f"const uint8_t {sym}[] = {{\n")
            for i in range(0, len(data), 20):
                c.write("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
            c.write("};\n")
            c.write(f"const size_t {sym}_len = {len(data)};\n")
        print(f"  {rel}: {len(data)} bytes")
    print(f"wrote {len(ASSETS)} emb_*.c files ({total} bytes of assets)")


if __name__ == "__main__":
    main()
